/**
 * Gateway-owned tool-call identifiers (specification section 12.4).
 *
 * Every emitted tool call carries a `call_ciq_<ULID>` id generated by the
 * gateway; an upstream-provided id is never trusted or reused. The generator is
 * a seam so deterministic tests can inject a fixed sequence. The ULID suffix
 * carries no request/thread/user/prompt information.
 */
import { ulid } from "ulid";

/** Prefix for gateway tool-call identifiers. */
export const TOOL_CALL_ID_PREFIX = "call_ciq_";

/** Produces unique, opaque `call_ciq_<ULID>` tool-call identifiers. */
export interface ToolCallIdGenerator {
  toolCallId(): string;
}

/**
 * Build a tool-call id generator. `next` defaults to a real ULID generator; a
 * test injects a deterministic sequence. The suffix is content-free.
 */
export function createToolCallIdGenerator(next: () => string = ulid): ToolCallIdGenerator {
  return {
    toolCallId: () => `${TOOL_CALL_ID_PREFIX}${next()}`,
  };
}
